-- AI Trend Analyzer - Shared Database Schema
-- This file is the contract between the Next.js frontend (trend) and the Python Agent backend (ai-trend-agent).
-- Both repos should validate against this schema.

CREATE EXTENSION IF NOT EXISTS vector;

-- Raw scraped entries before LLM processing
CREATE TABLE raw_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL CHECK (source IN ('producthunt', 'github', 'x', 'rss')),
  title TEXT NOT NULL,
  description TEXT,
  url TEXT UNIQUE NOT NULL,
  scraped_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Products that passed the AI-native filter
CREATE TABLE ai_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  raw_source_id UUID REFERENCES raw_sources(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  url TEXT UNIQUE NOT NULL,
  source TEXT NOT NULL,
  is_ai_native BOOLEAN NOT NULL DEFAULT true,
  innovation_score INTEGER NOT NULL CHECK (innovation_score BETWEEN 1 AND 10),
  core_capability TEXT,
  reasoning TEXT,
  discovered_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Atomic functions extracted from each AI product (Unbundling)
CREATE TABLE atomic_functions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES ai_products(id) ON DELETE CASCADE,
  function_name TEXT NOT NULL,
  category TEXT,
  pain_point TEXT,
  disposable_score INTEGER NOT NULL CHECK (disposable_score BETWEEN 1 AND 10),
  embedding vector(1536),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Clusters of related atomic functions (Re-bundling opportunities)
CREATE TABLE clusters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  label TEXT NOT NULL,
  description TEXT,
  is_whitespace BOOLEAN NOT NULL DEFAULT false,
  opportunity_score INTEGER CHECK (opportunity_score BETWEEN 1 AND 10),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Many-to-many: which atomic functions belong to which cluster
CREATE TABLE cluster_members (
  cluster_id UUID NOT NULL REFERENCES clusters(id) ON DELETE CASCADE,
  atomic_function_id UUID NOT NULL REFERENCES atomic_functions(id) ON DELETE CASCADE,
  PRIMARY KEY (cluster_id, atomic_function_id)
);

-- Re-bundling opportunity details derived from clusters
CREATE TABLE re_bundling_opportunities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cluster_id UUID NOT NULL REFERENCES clusters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  value_proposition TEXT,
  target_industry TEXT,
  moat_score INTEGER CHECK (moat_score BETWEEN 1 AND 10),
  has_proprietary_data BOOLEAN DEFAULT false,
  has_transaction_embed BOOLEAN DEFAULT false,
  has_network_effect BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Daily intelligence briefings generated by the agent
CREATE TABLE briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL UNIQUE,
  content_md TEXT NOT NULL,
  products_count INTEGER NOT NULL DEFAULT 0,
  opportunities_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- User feedback for the Reflection Loop
CREATE TABLE user_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  briefing_id UUID REFERENCES briefings(id) ON DELETE SET NULL,
  feedback_text TEXT NOT NULL,
  applied BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_products_discovered ON ai_products(discovered_at DESC);
CREATE INDEX idx_atomic_functions_embedding ON atomic_functions USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_briefings_date ON briefings(date DESC);
CREATE INDEX idx_user_feedback_applied ON user_feedback(applied) WHERE applied = false;
